import Navbar from "@/components/container/navbar/Navbar";
import Footer from "@/components/container/footer/Footer";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./Providers";
import { ClerkProvider, SignIn } from "@clerk/nextjs";
import { esES } from "@clerk/localizations";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider localization={esES}>
      <html lang="en">
        <body className={inter.className}>
          <Providers>
            <header className="sticky top-0 z-50">
              <Navbar />
            </header>
            {children}
            <Footer />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
